### ISSUE TITLE
realme 5 pro

### ISSUE THREAD

**Issue by Jordibgzashtita** [ij-israfil/android_kernel_realme_sdm710#1]
Hi

I mergef your kernel try see if there will be new updates https://github.com/Jordibgzashtita/kernel_realme_sdm710/tree/merge and it give like white screen on scratch custom ROM run.... Do you know why ..... It is realme 5 pro rmx1971....  Maybe sepooicy error or some kernel file has changed it config. thank

**Comment by ij-israfil** [comment]
Realme 5 pro has different display driver. Maybe that cause the issue.
